# ~/.config/starship.toml

# GLOBAL SETTINGS
add_newline = true
scan_timeout = 10
command_timeout = 1000

format = """
[î‚¶](#0f0f0f)$directory[î‚°](#0f0f0f)$git_branch$git_status$nodejs$python$golang$docker_context$package$cmd_duration$line_break$jobs$battery$time$character
"""

# PROMPT SYMBOL
[character]
success_symbol = "[î‚¶î•î‚´](bg:#0f0f0f fg:white)"
error_symbol = "[î‚¶âœ—î‚´](bg:#0f0f0f fg:red)"
vicmd_symbol = "[î‚¶â®î‚´](bg:#0f0f0f fg:yellow)"

# FONT
[username]
style_user = "bold white"
show_always = false

# DIRECTORY MODULE
[directory]
style = "bold white bg:#0f0f0f"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = "ğŸ”’"

# GIT BRANCH
[git_branch]
symbol = "ï˜ "
style = "white"
format = " [$symbol$branch]($style) "

# GIT STATUS
[git_status]
style = "bold white"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "âš”"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = "ï”© ${count}"
stashed = "ğŸ“¦ "
modified = "ï‘™ ${count}"
staged = "âœ” ${count}"
renamed = "ï•“ ${count}"
deleted = "ï€ ${count}"

# NODEJS
[nodejs]
symbol = "îœ˜ "
style = "bold green"
format = "[$symbol($version)]($style) "

# PYTHON
[python]
symbol = "îœ¼ "
style = "bold blue"
format = "[$symbol$version]($style) "

# GOLANG
[golang]
symbol = "î˜§ "
style = "bold cyan"
format = "[$symbol$version]($style) "

# DOCKER
[docker_context]
symbol = "ïŒˆ "
style = "blue"
format = "[$symbol$context]($style) "

# PACKAGE VERSION
[package]
symbol = "ï£– "
style = "white"
format = "[$symbol$version]($style) "

# COMMAND DURATION
[cmd_duration]
min_time = 1000
style = "bold yellow"
format = "[took $duration]($style) "

# JOBS
[jobs]
symbol = "âœ¦"
style = "bold red"

# BATTERY
[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡"
discharging_symbol = "ğŸ”Œ"
unknown_symbol = "â“"
empty_symbol = "ï‰„"

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

# TIME
[time]
disabled = false
format = "[ğŸ•’ $time]($style) "
time_format = "%H:%M"
style = "white"
